/**
 * MCP tool: generate_robots_txt
 *
 * Produces a clean, policy-driven robots.txt:
 *   - Explicit allow blocks for trusted search & social bots.
 *   - Explicit block blocks for high-risk AI / scraper bots (configurable).
 *   - Optional Crawl-delay for SEO tools.
 *   - Sitemap declarations.
 */

import { z } from "zod";

import { KNOWN_BOTS } from "../data/known-bots.js";
import type { BotSignature } from "../utils/types.js";
import { defineTool, ok } from "./tool-types.js";

const Input = z.object({
  siteUrl: z.string().url().optional(),
  blockAi: z
    .boolean()
    .default(false)
    .describe("Disallow AI training crawlers (GPTBot, ClaudeBot, Google-Extended, etc.)."),
  blockSeo: z
    .boolean()
    .default(false)
    .describe("Disallow SEO crawlers (AhrefsBot, SemrushBot, etc.)."),
  blockScrapers: z
    .boolean()
    .default(true)
    .describe("Disallow known data scrapers / lead gen."),
  blockSecurityScanners: z
    .boolean()
    .default(true)
    .describe("Disallow Internet-wide security scanners (Shodan, Censys)."),
  extraDisallowUserAgents: z
    .array(z.string())
    .default([])
    .describe("Additional bot User-Agent tokens to Disallow."),
  extraDisallowPaths: z
    .array(z.string())
    .default([
      "/api/",
      "/dashboard/",
      "/admin/",
      "/admin",
      "/reset-password",
      "/cdn-cgi/",
      "/search",
      "/search?*",
    ])
    .describe(
      "Paths to Disallow for everyone. Defaults to hellogrowthcrm.com's actual disallow list.",
    ),
  crawlDelaySeconds: z
    .number()
    .min(0)
    .max(86400)
    .optional()
    .describe("Optional Crawl-delay applied to all bots."),
  sitemapUrls: z
    .array(z.string().url())
    .default(["https://hellogrowthcrm.com/sitemap-index.xml"])
    .describe("Sitemap URLs to declare. Defaults to hellogrowthcrm.com's sitemap index."),
});

type GenInput = z.infer<typeof Input>;

export const generateRobotsTxt = defineTool({
  schema: Input,
  definition: {
    name: "generate_robots_txt",
    description:
      "Generate a production-ready robots.txt that explicitly allows trusted bots, blocks chosen categories (AI, SEO, scrapers), and declares sitemaps.",
    inputSchema: {
      type: "object",
      properties: {
        siteUrl: { type: "string", format: "uri" },
        blockAi: { type: "boolean", default: false },
        blockSeo: { type: "boolean", default: false },
        blockScrapers: { type: "boolean", default: true },
        blockSecurityScanners: { type: "boolean", default: true },
        extraDisallowUserAgents: {
          type: "array",
          items: { type: "string" },
          default: [],
        },
        extraDisallowPaths: {
          type: "array",
          items: { type: "string" },
          default: [],
        },
        crawlDelaySeconds: { type: "number", minimum: 0, maximum: 86400 },
        sitemapUrls: {
          type: "array",
          items: { type: "string", format: "uri" },
          default: [],
        },
      },
      additionalProperties: false,
    },
  },
  async handle(args) {
    const siteUrl = args.siteUrl ?? process.env.DEFAULT_TARGET_URL ?? "https://hellogrowthcrm.com";
    const out: string[] = [
      "# robots.txt — generated by hellogrowthcrm-bot-crawler",
      `# Generated at ${new Date().toISOString()}`,
      `# Site: ${siteUrl}`,
      "",
    ];

    out.push("User-agent: *");
    out.push("Allow: /");
    for (const p of args.extraDisallowPaths) {
      out.push(`Disallow: ${normalizePath(p)}`);
    }
    if (args.crawlDelaySeconds !== undefined) {
      out.push(`Crawl-delay: ${args.crawlDelaySeconds}`);
    }
    out.push("");

    // Build the block list.
    const blockList: { name: string; reason: string }[] = [];
    for (const bot of KNOWN_BOTS) {
      const reason = blockReason(bot, args);
      if (reason) blockList.push({ name: primaryToken(bot), reason });
    }
    for (const extra of args.extraDisallowUserAgents) {
      blockList.push({ name: extra, reason: "user-supplied block" });
    }

    if (blockList.length) {
      out.push("# --- Blocked bots --------------------------------------------------");
      for (const b of blockList) {
        out.push(`# ${b.name}: ${b.reason}`);
        out.push(`User-agent: ${b.name}`);
        out.push("Disallow: /");
        out.push("");
      }
    }

    for (const sm of args.sitemapUrls) out.push(`Sitemap: ${sm}`);
    if (args.sitemapUrls.length) out.push("");

    return ok({
      siteUrl,
      robotsTxt: out.join("\n"),
      blockedBots: blockList.map((b) => b.name),
      note:
        `Save this content to /robots.txt at the root of ${siteUrl}. Remember: robots.txt is advisory — bots that ignore it must be blocked at the firewall / CDN layer.`,
    });
  },
});

function blockReason(bot: BotSignature, args: GenInput): string | null {
  if (args.blockAi && bot.category === "ai") return "AI training / inference crawler";
  if (args.blockSeo && bot.category === "seo") return "SEO crawler";
  if (args.blockScrapers && bot.category === "scraper") return "Known scraper";
  if (args.blockSecurityScanners && bot.category === "security") {
    return "Internet-wide security scanner";
  }
  return null;
}

function primaryToken(bot: BotSignature): string {
  // Use the bot's canonical name as the robots.txt token. For Google-Extended
  // and Applebot-Extended this exactly matches the documented opt-out token.
  return bot.name;
}

function normalizePath(p: string): string {
  return p.startsWith("/") ? p : `/${p}`;
}
